-- AI router history used by the server-side /api/ai task router.

begin;

create table if not exists public.ai_router_history (
  turn_id bigint generated by default as identity primary key,
  session_id text not null,
  user_query text not null,
  intent text not null,
  api_call jsonb,
  api_result_summary text,
  assistant_message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_ai_router_history_session_turn
  on public.ai_router_history (session_id, turn_id desc);

create index if not exists idx_ai_router_history_intent
  on public.ai_router_history (intent);

create index if not exists idx_ai_router_history_user_query
  on public.ai_router_history using gin (to_tsvector('simple', coalesce(user_query, '')));

alter table public.ai_router_history enable row level security;

comment on table public.ai_router_history is 'Server-side AI router history for Finca assistant turns.';
comment on column public.ai_router_history.api_call is 'Planned or executed upstream calls recorded by the AI router.';
comment on column public.ai_router_history.metadata is 'Structured metadata such as batch_id, event_type, ui_action, and hash references.';

commit;
